# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/jdamata/ecrgate
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - run: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Build and push Docker image
          command: |
            TAG=$(git rev-parse --short HEAD)
            docker build -t jdamata/ecrgate:$TAG .
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push jdamata/ecrgate:$TAG
